
import { Recipe } from '../types/recipe';

const additionalRecipes: Recipe[] = [
  {
    id: "moroccan-tagine",
    title: "Moroccan Lamb Tagine",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    ingredients: [
      "2 lbs lamb shoulder, cut into 1-inch cubes",
      "2 tbsp olive oil",
      "2 onions, sliced",
      "4 cloves garlic, minced",
      "2 tbsp ginger, minced",
      "1 tsp ground cinnamon",
      "1 tsp ground cumin",
      "1 tsp ground coriander",
      "1 tsp paprika",
      "1/2 tsp turmeric",
      "1/4 tsp cayenne pepper",
      "1 can (14 oz) diced tomatoes",
      "2 cups chicken stock",
      "3 tbsp honey",
      "1 cup dried apricots, chopped",
      "1 cup pitted green olives",
      "1 lemon, zested and juiced",
      "1/4 cup fresh cilantro, chopped",
      "1/4 cup fresh mint, chopped",
      "Salt and pepper to taste"
    ],
    steps: [
      "Heat olive oil in a large Dutch oven or tagine pot over medium-high heat.",
      "Season lamb with salt and pepper, then brown in batches, about 5 minutes per batch. Transfer to a plate.",
      "Add onions to the pot and cook until softened, about 5 minutes.",
      "Add garlic and ginger, cook for 1 minute until fragrant.",
      "Stir in cinnamon, cumin, coriander, paprika, turmeric, and cayenne pepper. Cook for 1 minute.",
      "Return lamb to the pot and add diced tomatoes, chicken stock, and honey. Bring to a boil.",
      "Reduce heat to low, cover, and simmer for 1.5 hours or until lamb is tender.",
      "Add apricots and olives, continue to simmer for 30 minutes.",
      "Stir in lemon zest, lemon juice, cilantro, and mint.",
      "Adjust seasoning with salt and pepper.",
      "Serve over couscous or with flatbread."
    ],
    cuisine: "Moroccan",
    tags: ["Meat", "Stew", "Special Occasion"],
    prepTime: 150
  },
  {
    id: "brazilian-feijoada",
    title: "Brazilian Feijoada",
    image: "https://images.unsplash.com/photo-1599122759357-33bbd23d2cd5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    ingredients: [
      "2 cups dried black beans, soaked overnight",
      "1 lb pork shoulder, cubed",
      "1/2 lb smoked sausage, sliced",
      "1/4 lb bacon, diced",
      "1 onion, chopped",
      "4 cloves garlic, minced",
      "2 bay leaves",
      "1 orange, peeled and separated into segments",
      "2 tbsp olive oil",
      "Salt and pepper to taste",
      "Cooked white rice, for serving",
      "Orange slices, for garnish",
      "Collard greens, thinly sliced and sautéed",
      "Farofa (toasted cassava flour)"
    ],
    steps: [
      "Drain and rinse the soaked beans.",
      "In a large pot, cook bacon over medium heat until crispy. Remove and set aside.",
      "In the same pot, brown pork shoulder pieces in batches. Set aside.",
      "Add olive oil if needed, then sauté onion and garlic until softened.",
      "Return beans, pork, bacon, and sausage to the pot. Add bay leaves.",
      "Add enough water to cover ingredients by about 2 inches.",
      "Bring to a boil, then reduce heat to low, cover and simmer for about 2-3 hours until beans and meat are tender.",
      "Add orange segments in the last 30 minutes of cooking.",
      "Season with salt and pepper.",
      "Serve over rice with collard greens, farofa, and orange slices."
    ],
    cuisine: "Brazilian",
    tags: ["Meat", "Stew", "National Dish"],
    prepTime: 180
  },
  {
    id: "japanese-ramen",
    title: "Authentic Japanese Ramen",
    image: "https://images.unsplash.com/photo-1557872943-16a5ac26437e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    ingredients: [
      "2 lbs pork bones",
      "1 lb chicken bones",
      "2 onions, halved",
      "2 carrots, roughly chopped",
      "4 cloves garlic, smashed",
      "2-inch piece ginger, sliced",
      "2 tbsp vegetable oil",
      "1/4 cup sake",
      "1/4 cup mirin",
      "1/4 cup soy sauce",
      "2 tbsp miso paste",
      "1 tbsp sesame oil",
      "Salt to taste",
      "1 lb fresh ramen noodles",
      "For toppings: sliced pork belly (chashu), soft-boiled eggs, nori sheets, scallions, bean sprouts, corn, bamboo shoots"
    ],
    steps: [
      "Rinse pork and chicken bones under cold water.",
      "Roast bones, onions, carrots, garlic, and ginger in a 450°F oven for 30-40 minutes until browned.",
      "Transfer roasted ingredients to a large stockpot and add enough water to cover by 2 inches.",
      "Bring to a boil, then reduce heat to low. Simmer for 6-8 hours, skimming foam occasionally.",
      "Strain broth through a fine-mesh sieve into a clean pot.",
      "Add sake, mirin, soy sauce, and simmer for 30 minutes.",
      "Whisk in miso paste and sesame oil. Season with salt to taste.",
      "Cook ramen noodles according to package instructions.",
      "Assemble bowls: place cooked noodles, ladle hot broth over them, and arrange toppings as desired."
    ],
    cuisine: "Japanese",
    tags: ["Soup", "Noodles", "Comfort Food"],
    prepTime: 480
  },
  {
    id: "indian-butter-chicken",
    title: "Indian Butter Chicken (Murgh Makhani)",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    ingredients: [
      "2 lbs boneless chicken thighs, cut into 2-inch pieces",
      "1 cup plain yogurt",
      "2 tbsp lemon juice",
      "2 tsp ground turmeric",
      "2 tbsp garam masala",
      "2 tbsp ground cumin",
      "2 tbsp ground coriander",
      "4 cloves garlic, minced",
      "2 tbsp ginger, minced",
      "1/2 cup butter",
      "1 large onion, finely chopped",
      "2 cans (14 oz each) tomato sauce",
      "1 cup heavy cream",
      "2 tbsp tomato paste",
      "1 tbsp sugar",
      "Salt to taste",
      "1/4 cup fresh cilantro, chopped",
      "Naan bread and rice for serving"
    ],
    steps: [
      "In a bowl, mix yogurt, lemon juice, turmeric, 1 tbsp garam masala, 1 tbsp cumin, 1 tbsp coriander, half the garlic, and half the ginger.",
      "Add chicken to the marinade, coat well, and refrigerate for at least 2 hours or overnight.",
      "Preheat grill or broiler. Thread chicken onto skewers and grill until charred but not fully cooked, about 5 minutes per side.",
      "In a large pot, melt butter over medium heat. Add onions and cook until soft, about 5 minutes.",
      "Add remaining garlic, ginger, garam masala, cumin, and coriander. Cook for 1 minute until fragrant.",
      "Stir in tomato sauce, tomato paste, and sugar. Simmer for 15 minutes.",
      "Add grilled chicken pieces, including any juices. Simmer for 10-15 minutes until chicken is fully cooked.",
      "Stir in heavy cream and simmer for 5 more minutes.",
      "Season with salt and garnish with cilantro.",
      "Serve with naan bread and rice."
    ],
    cuisine: "Indian",
    tags: ["Curry", "Spicy", "Comfort Food"],
    prepTime: 60
  },
  {
    id: "mexican-mole-poblano",
    title: "Mexican Mole Poblano",
    image: "https://images.unsplash.com/photo-1545093149-618ce3bcf49d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    ingredients: [
      "4 chicken breasts or 8 chicken thighs",
      "4 dried ancho chiles, stemmed and seeded",
      "3 dried guajillo chiles, stemmed and seeded",
      "2 dried chipotle chiles, stemmed and seeded",
      "1/4 cup sesame seeds",
      "1/4 cup pumpkin seeds",
      "2 corn tortillas, torn into pieces",
      "1 onion, chopped",
      "3 cloves garlic, minced",
      "2 tomatoes, chopped",
      "1/4 cup raisins",
      "1/4 cup almonds",
      "2 oz dark chocolate (70% cocoa or higher), chopped",
      "1 cinnamon stick",
      "1/4 tsp ground cloves",
      "1/4 tsp ground allspice",
      "4 cups chicken broth",
      "2 tbsp vegetable oil",
      "Salt to taste",
      "Rice and warm tortillas for serving"
    ],
    steps: [
      "Toast dried chiles in a dry skillet over medium heat until fragrant, about 2-3 minutes. Transfer to a bowl, cover with hot water, and soak for 30 minutes.",
      "In the same skillet, toast sesame seeds, pumpkin seeds, and torn tortillas until golden. Set aside.",
      "Heat 1 tbsp oil in the skillet. Cook onion and garlic until soft, about 5 minutes.",
      "Add tomatoes, raisins, almonds, chocolate, cinnamon stick, cloves, and allspice. Cook for 5 minutes.",
      "Drain soaked chiles, reserving 1 cup of soaking liquid.",
      "In a blender, combine chile mixture, toasted seeds and tortillas, and the tomato-spice mixture. Add reserved chile soaking liquid and blend until smooth.",
      "Heat remaining oil in a large pot. Strain sauce through a fine-mesh sieve into the pot.",
      "Simmer sauce for 30 minutes, stirring occasionally.",
      "Add chicken broth gradually to achieve desired consistency. Simmer for another 30 minutes.",
      "Meanwhile, season chicken with salt and pepper and cook separately.",
      "Add cooked chicken to mole sauce, simmer for 10 minutes.",
      "Serve chicken with mole sauce over rice, sprinkled with sesame seeds."
    ],
    cuisine: "Mexican",
    tags: ["Spicy", "Special Occasion", "Traditional"],
    prepTime: 120
  },
  {
    id: "french-coq-au-vin",
    title: "French Coq au Vin",
    image: "https://images.unsplash.com/photo-1574484284002-952d92456975?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    ingredients: [
      "1 whole chicken (about 4 lbs), cut into 8 pieces",
      "8 oz bacon, diced",
      "2 cups pearl onions, peeled",
      "8 oz cremini mushrooms, quartered",
      "2 carrots, sliced",
      "2 celery stalks, sliced",
      "4 cloves garlic, minced",
      "1 bottle (750 ml) dry red wine (Burgundy or Pinot Noir)",
      "2 cups chicken stock",
      "2 tbsp tomato paste",
      "1 bouquet garni (4 sprigs thyme, 2 sprigs rosemary, 2 bay leaves tied together)",
      "3 tbsp flour",
      "3 tbsp butter, softened",
      "1/4 cup brandy",
      "2 tbsp fresh parsley, chopped",
      "Salt and pepper to taste"
    ],
    steps: [
      "Season chicken pieces with salt and pepper.",
      "In a large Dutch oven, cook bacon over medium heat until crispy. Remove and set aside.",
      "Brown chicken pieces in bacon fat, working in batches, about 5 minutes per side. Transfer to a plate.",
      "Add pearl onions to the pot and cook until browned, about 5 minutes. Remove and set aside.",
      "Add mushrooms and cook until golden, about 5 minutes. Remove and set aside.",
      "Add carrots, celery, and garlic to the pot. Cook for 5 minutes.",
      "Add brandy and carefully ignite to burn off alcohol (optional).",
      "Pour in red wine, chicken stock, and tomato paste. Stir to combine.",
      "Return chicken to the pot along with the bouquet garni. Bring to a simmer.",
      "Reduce heat to low, cover, and simmer for 1.5 hours until chicken is very tender.",
      "In a small bowl, mash together butter and flour to form a paste (beurre manié).",
      "Remove chicken from pot and keep warm.",
      "Increase heat and bring liquid to a boil. Whisk in butter-flour mixture bit by bit until sauce thickens.",
      "Return chicken, bacon, pearl onions, and mushrooms to the pot. Simmer for 10 more minutes.",
      "Remove bouquet garni, adjust seasoning, and garnish with parsley.",
      "Serve with mashed potatoes or crusty bread."
    ],
    cuisine: "French",
    tags: ["Chicken", "Wine", "Special Occasion"],
    prepTime: 150
  },
  {
    id: "korean-bibimbap",
    title: "Korean Bibimbap",
    image: "https://images.unsplash.com/photo-1553163147-622ab57be1c4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    ingredients: [
      "2 cups short-grain rice, cooked",
      "1/2 lb beef sirloin, thinly sliced",
      "2 tbsp soy sauce",
      "2 tbsp sesame oil",
      "2 cloves garlic, minced",
      "1 tbsp sugar",
      "2 cups spinach, blanched and seasoned",
      "2 cups bean sprouts, blanched and seasoned",
      "1 carrot, julienned and sautéed",
      "1 zucchini, julienned and sautéed",
      "1 cucumber, julienned",
      "4 eggs",
      "4 tbsp vegetable oil",
      "1 cup kimchi",
      "Gochujang (Korean red pepper paste) to taste",
      "Toasted sesame seeds for garnish"
    ],
    steps: [
      "Marinate beef in soy sauce, 1 tbsp sesame oil, garlic, and sugar for 30 minutes.",
      "Prepare vegetables: Blanch spinach and bean sprouts separately, then season with salt and sesame oil.",
      "Sauté carrots and zucchini separately until tender-crisp, season with salt.",
      "Heat 1 tbsp oil in a skillet and cook marinated beef until browned.",
      "Fry eggs sunny-side up in remaining oil.",
      "Assemble bibimbap bowls: Place warm rice in the bottom of each bowl.",
      "Arrange beef and vegetables in separate sections on top of rice.",
      "Place a fried egg in the center of each bowl.",
      "Serve with kimchi and gochujang on the side.",
      "To eat, mix everything together thoroughly before enjoying."
    ],
    cuisine: "Korean",
    tags: ["Rice Bowl", "Healthy", "Spicy"],
    prepTime: 60
  },
  {
    id: "lebanese-mezze",
    title: "Lebanese Mezze Platter",
    image: "https://images.unsplash.com/photo-1542528180-a1208c5169a5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    ingredients: [
      "For Hummus:",
      "1 can (15 oz) chickpeas, drained",
      "1/4 cup tahini",
      "3 tbsp lemon juice",
      "2 cloves garlic",
      "2 tbsp olive oil",
      "Salt to taste",
      
      "For Baba Ganoush:",
      "2 medium eggplants",
      "1/4 cup tahini",
      "2 tbsp lemon juice",
      "2 cloves garlic, minced",
      "2 tbsp olive oil",
      "Salt to taste",
      
      "For Tabbouleh:",
      "1 cup bulgur wheat",
      "2 cups fresh parsley, chopped",
      "1/2 cup fresh mint, chopped",
      "3 tomatoes, diced",
      "1 cucumber, diced",
      "4 green onions, sliced",
      "1/4 cup olive oil",
      "1/4 cup lemon juice",
      
      "For Serving:",
      "Warm pita bread",
      "Olives",
      "Feta cheese",
      "Fresh vegetables for dipping"
    ],
    steps: [
      "Make Hummus: Blend chickpeas, tahini, lemon juice, garlic, and salt in a food processor. Slowly add olive oil until smooth.",
      "Make Baba Ganoush: Prick eggplants and roast at 450°F for 45 minutes until skin is charred. Scoop out flesh and blend with tahini, lemon juice, garlic, olive oil, and salt.",
      "Make Tabbouleh: Soak bulgur in hot water for 30 minutes, then drain. Mix with chopped herbs, vegetables, olive oil, and lemon juice.",
      "Arrange hummus, baba ganoush, and tabbouleh in separate bowls.",
      "Add olives, feta cheese, and fresh vegetables to the platter.",
      "Serve with warm pita bread."
    ],
    cuisine: "Lebanese",
    tags: ["Appetizer", "Vegetarian", "Sharing"],
    prepTime: 80
  },
  {
    id: "ethiopian-doro-wat",
    title: "Ethiopian Doro Wat (Spicy Chicken Stew)",
    image: "https://images.unsplash.com/photo-1515516969-d4008cc6241a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    ingredients: [
      "2 lbs chicken, cut into pieces",
      "1/4 cup lemon juice",
      "2 tsp salt",
      "3 large onions, finely chopped",
      "1/4 cup niter kibbeh (Ethiopian spiced butter) or regular butter",
      "1/4 cup vegetable oil",
      "3 tbsp berbere spice blend",
      "1 tbsp minced garlic",
      "1 tbsp minced ginger",
      "1/2 cup red wine",
      "1 cup chicken stock",
      "4 hard-boiled eggs, peeled",
      "Injera (Ethiopian flatbread) for serving"
    ],
    steps: [
      "Rub chicken with lemon juice and salt. Set aside for 30 minutes.",
      "In a large pot, cook onions without oil over low heat for about 45 minutes, stirring occasionally, until deeply caramelized.",
      "Add niter kibbeh (or regular butter) and oil to the onions. Increase heat to medium.",
      "Stir in berbere spice, garlic, and ginger. Cook for 2-3 minutes until fragrant.",
      "Add chicken pieces and brown on all sides, about 5 minutes.",
      "Pour in red wine and chicken stock. Bring to a simmer.",
      "Reduce heat to low, cover, and simmer for 45 minutes, until chicken is very tender.",
      "Make small incisions in the hard-boiled eggs and add them to the stew.",
      "Simmer for 15 more minutes to allow the eggs to absorb the flavors.",
      "Serve hot with injera flatbread on the side."
    ],
    cuisine: "Ethiopian",
    tags: ["Spicy", "Stew", "Traditional"],
    prepTime: 120
  },
  {
    id: "spanish-paella",
    title: "Spanish Seafood Paella",
    image: "https://images.unsplash.com/photo-1515669097368-22e68427d265?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    ingredients: [
      "3 cups short-grain rice (preferably Spanish Bomba)",
      "6 cups fish stock or chicken stock",
      "1 tsp saffron threads",
      "1/4 cup olive oil",
      "1 onion, chopped",
      "3 cloves garlic, minced",
      "1 red bell pepper, sliced",
      "2 tomatoes, diced",
      "1 tsp smoked paprika",
      "1 tsp ground turmeric",
      "12 large shrimp, shell-on",
      "12 mussels, cleaned",
      "8 oz calamari, sliced into rings",
      "8 oz firm white fish (like cod), cut into chunks",
      "1 cup frozen peas",
      "1 lemon, cut into wedges",
      "1/4 cup fresh parsley, chopped",
      "Salt and pepper to taste"
    ],
    steps: [
      "Heat stock in a pot and infuse with saffron. Keep warm.",
      "Heat olive oil in a 15-inch paella pan over medium-high heat.",
      "Sauté onion until softened, about 5 minutes.",
      "Add garlic, bell pepper, and tomatoes. Cook for 3 minutes.",
      "Add paprika and turmeric, stir quickly.",
      "Add rice and stir to coat with oil and vegetables.",
      "Pour in warm saffron-infused stock, bring to a boil.",
      "Reduce heat to medium-low and simmer for 10 minutes without stirring.",
      "Arrange seafood on top of the rice, pressing slightly into the mixture.",
      "Sprinkle peas over the top.",
      "Continue cooking for 10-15 more minutes until rice is al dente and seafood is cooked.",
      "Remove from heat, cover with a cloth, and let rest for 5 minutes.",
      "Garnish with lemon wedges and parsley before serving."
    ],
    cuisine: "Spanish",
    tags: ["Seafood", "Rice", "Special Occasion"],
    prepTime: 60
  },
  {
    id: "turkish-manti",
    title: "Turkish Manti (Dumpling)",
    image: "https://images.unsplash.com/photo-1594246243580-77085e7fe507?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    ingredients: [
      "For the dough:",
      "3 cups all-purpose flour",
      "1 egg",
      "3/4 cup water",
      "1 tsp salt",
      
      "For the filling:",
      "1 lb ground lamb or beef",
      "1 onion, grated",
      "2 cloves garlic, minced",
      "1/4 cup parsley, chopped",
      "1 tsp salt",
      "1/2 tsp black pepper",
      
      "For the yogurt sauce:",
      "2 cups Greek yogurt",
      "2 cloves garlic, minced",
      "Salt to taste",
      
      "For the butter sauce:",
      "4 tbsp butter",
      "1 tbsp paprika",
      "1 tbsp dried mint",
      "Red pepper flakes to taste"
    ],
    steps: [
      "Make the dough: Combine flour and salt, then add egg and water. Knead until smooth, then rest for 30 minutes covered.",
      "Make the filling: Mix ground meat, grated onion, garlic, parsley, salt, and pepper.",
      "Roll out dough very thin, cut into 2-inch squares.",
      "Place a small amount of filling (about 1/2 tsp) in the center of each square.",
      "Fold corners to the center and pinch to seal, forming a small dumpling.",
      "Bring a large pot of salted water to a boil and cook manti for about 8-10 minutes until tender.",
      "Meanwhile, prepare yogurt sauce by mixing yogurt with garlic and salt.",
      "Heat butter in a small pan, add paprika, mint, and red pepper flakes.",
      "Drain manti and transfer to serving dishes.",
      "Top with garlicky yogurt sauce, then drizzle with spiced butter.",
      "Serve immediately."
    ],
    cuisine: "Turkish",
    tags: ["Dumpling", "Comfort Food", "Labor-intensive"],
    prepTime: 120
  },
  {
    id: "jamaican-jerk-chicken",
    title: "Jamaican Jerk Chicken",
    image: "https://images.unsplash.com/photo-1575985757656-a657d5756305?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    ingredients: [
      "4 lbs chicken pieces (thighs and drumsticks)",
      "6 scallions, roughly chopped",
      "4 cloves garlic",
      "2 Scotch bonnet peppers, seeds removed (use gloves!)",
      "1 small onion, quartered",
      "2-inch piece ginger, peeled",
      "2 tbsp fresh thyme leaves",
      "2 tbsp brown sugar",
      "2 tbsp allspice berries",
      "1 tbsp black peppercorns",
      "1 tsp ground cinnamon",
      "1/2 tsp ground nutmeg",
      "2 tbsp soy sauce",
      "1/4 cup orange juice",
      "1/4 cup lime juice",
      "1/4 cup vegetable oil",
      "Salt to taste",
      "Lime wedges for serving"
    ],
    steps: [
      "Make jerk marinade: Blend scallions, garlic, peppers, onion, ginger, thyme, brown sugar, allspice, peppercorns, cinnamon, nutmeg, soy sauce, orange juice, lime juice, oil, and salt until smooth.",
      "Make small cuts in chicken pieces to allow marinade to penetrate.",
      "Place chicken in a large ziplock bag and pour marinade over. Seal and massage to coat chicken thoroughly.",
      "Refrigerate for at least 4 hours, preferably overnight.",
      "Preheat grill to medium heat. For authentic flavor, add soaked pimento wood chips to charcoal.",
      "Remove chicken from marinade, reserving excess marinade.",
      "Grill chicken for about 30-40 minutes, turning occasionally and basting with reserved marinade, until fully cooked (165°F internal temperature).",
      "Alternatively, bake in a 375°F oven for about 45 minutes.",
      "Let chicken rest for 10 minutes before serving.",
      "Serve with lime wedges, rice and peas, and festival (Jamaican fried dumplings)."
    ],
    cuisine: "Jamaican",
    tags: ["Spicy", "Grilled", "Marinated"],
    prepTime: 60
  },
  {
    id: "vietnamese-pho",
    title: "Vietnamese Pho Bo (Beef Noodle Soup)",
    image: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    ingredients: [
      "For the broth:",
      "2 lbs beef bones (marrow and knuckle)",
      "1 lb beef brisket",
      "2 onions, halved",
      "1 4-inch piece ginger, halved lengthwise",
      "5 star anise pods",
      "1 cinnamon stick",
      "3 whole cloves",
      "1 tbsp coriander seeds",
      "1 tbsp fennel seeds",
      "2 tbsp fish sauce",
      "1 tbsp sugar",
      "Salt to taste",
      
      "For serving:",
      "1 lb rice noodles, cooked according to package instructions",
      "1/2 lb beef sirloin, very thinly sliced",
      "2 cups bean sprouts",
      "1 bunch fresh Thai basil",
      "1 bunch fresh cilantro",
      "1 bunch fresh mint",
      "2 limes, cut into wedges",
      "2 jalapeños, sliced",
      "Hoisin sauce and sriracha for serving"
    ],
    steps: [
      "Preheat oven to 425°F. Roast beef bones, onions, and ginger for 30 minutes until browned.",
      "Transfer bones, onions, and ginger to a large stockpot. Add 4 quarts of water and bring to a boil.",
      "Add brisket to the pot, reduce heat to low and simmer for 1.5 hours until brisket is tender. Remove brisket, let cool, then slice thinly.",
      "Continue simmering broth for 2-3 more hours, skimming as needed.",
      "Toast star anise, cinnamon, cloves, coriander, and fennel seeds in a dry skillet until fragrant. Add to the broth.",
      "After 3-4 total hours of simmering, strain broth through a fine-mesh sieve. Add fish sauce and sugar, adjust salt to taste.",
      "To serve, place cooked rice noodles in bowls, top with sliced brisket and raw sirloin.",
      "Pour hot broth over the meat (the heat will cook the raw sirloin).",
      "Serve with bean sprouts, herbs, lime wedges, jalapeños, hoisin sauce, and sriracha on the side for each person to add according to taste."
    ],
    cuisine: "Vietnamese",
    tags: ["Soup", "Comfort Food", "Traditional"],
    prepTime: 240
  },
  {
    id: "peruvian-ceviche",
    title: "Peruvian Ceviche",
    image: "https://images.unsplash.com/photo-1553639766-450abeeaf06d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    ingredients: [
      "1 lb fresh white fish fillets (sea bass, halibut, or flounder), cut into 1/2-inch cubes",
      "1 cup fresh lime juice (about 8-10 limes)",
      "1 red onion, thinly sliced",
      "2 cloves garlic, minced",
      "1-2 habanero or aji limo peppers, seeded and minced",
      "1/4 cup fresh cilantro, chopped",
      "1 tbsp fresh ginger, minced",
      "1 tsp salt",
      "1/2 tsp freshly ground black pepper",
      "1 sweet potato, boiled and sliced",
      "1 ear of corn, boiled and kernels cut off",
      "Lettuce leaves for serving"
    ],
    steps: [
      "In a glass bowl, combine fish and lime juice, making sure fish is completely submerged. Cover and refrigerate for 15-20 minutes until fish turns opaque.",
      "Add red onion, garlic, peppers, ginger, salt, and pepper to the fish mixture. Stir gently to combine.",
      "Refrigerate for an additional 5-10 minutes to allow flavors to meld.",
      "Just before serving, add chopped cilantro and stir gently.",
      "Serve ceviche in chilled bowls or glasses, garnished with sweet potato slices and corn kernels.",
      "Line plates with lettuce leaves and place ceviche on top.",
      "Traditional accompaniments include cancha (toasted corn) and chifles (plantain chips)."
    ],
    cuisine: "Peruvian",
    tags: ["Seafood", "No-cook", "Fresh"],
    prepTime: 40
  },
  {
    id: "russian-borscht",
    title: "Russian Borscht Soup",
    image: "https://images.unsplash.com/photo-1617793667536-4b1599be95b6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    ingredients: [
      "1 lb beef chuck, cubed",
      "8 cups beef broth",
      "1 large onion, chopped",
      "2 large carrots, grated",
      "3 medium beets, peeled and grated",
      "2 tbsp vegetable oil",
      "2 tbsp tomato paste",
      "1 tbsp white vinegar",
      "1 bay leaf",
      "3 medium potatoes, peeled and cubed",
      "1/2 small cabbage, shredded",
      "3 cloves garlic, minced",
      "Salt and pepper to taste",
      "Sour cream for serving",
      "Fresh dill for garnish",
      "Rye bread on the side"
    ],
    steps: [
      "In a large pot, combine beef, beef broth, and bay leaf. Bring to a boil, reduce heat, and simmer for 1 hour until meat is tender.",
      "Meanwhile, in a large skillet, heat oil over medium heat. Add onions and carrots, sauté for 5 minutes.",
      "Add beets to the skillet and cook for another 5 minutes.",
      "Stir in tomato paste and vinegar, cook for 1 minute. Set aside.",
      "Add potatoes to the broth and simmer for 15 minutes.",
      "Add cabbage and the beet mixture to the broth. Simmer for another 15 minutes until vegetables are tender.",
      "Add minced garlic and cook for 2 more minutes.",
      "Season with salt and pepper to taste.",
      "Let the soup rest for at least 15 minutes before serving.",
      "Serve hot with a dollop of sour cream, sprinkle of fresh dill, and rye bread on the side."
    ],
    cuisine: "Russian",
    tags: ["Soup", "Comfort Food", "Winter"],
    prepTime: 120
  },
  {
    id: "swedish-meatballs",
    title: "Swedish Meatballs with Lingonberry Sauce",
    image: "https://images.unsplash.com/photo-1515516969-d4008cc6241a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    ingredients: [
      "For meatballs:",
      "1 lb ground beef",
      "1/2 lb ground pork",
      "1 cup breadcrumbs",
      "1/2 cup milk",
      "1 egg",
      "1 onion, finely grated",
      "1/4 tsp ground allspice",
      "1/4 tsp ground nutmeg",
      "Salt and pepper to taste",
      "2 tbsp butter for frying",
      
      "For cream sauce:",
      "3 tbsp butter",
      "3 tbsp all-purpose flour",
      "2 cups beef broth",
      "1 cup heavy cream",
      "1 tbsp soy sauce",
      "1 tsp Dijon mustard",
      
      "For serving:",
      "Lingonberry jam",
      "Mashed potatoes or egg noodles",
      "Fresh dill for garnish"
    ],
    steps: [
      "In a bowl, combine breadcrumbs and milk. Let sit for 10 minutes until absorbed.",
      "Add ground beef, ground pork, grated onion, egg, allspice, nutmeg, salt, and pepper to the breadcrumb mixture. Mix gently until combined.",
      "Shape mixture into 1-inch meatballs.",
      "Heat butter in a large skillet over medium heat. Cook meatballs in batches, turning frequently, until browned on all sides and cooked through, about 8-10 minutes. Transfer to a plate.",
      "In the same skillet, melt 3 tbsp butter for the sauce.",
      "Whisk in flour and cook for 1-2 minutes until golden brown.",
      "Gradually whisk in beef broth, then add heavy cream, soy sauce, and Dijon mustard.",
      "Bring to a simmer and cook until sauce thickens, about 5-8 minutes.",
      "Return meatballs to the skillet and simmer for 5 more minutes.",
      "Serve with lingonberry jam, mashed potatoes or egg noodles, and garnish with fresh dill."
    ],
    cuisine: "Swedish",
    tags: ["Comfort Food", "Meatballs", "Traditional"],
    prepTime: 60
  },
  {
    id: "hawaiian-poke",
    title: "Hawaiian Ahi Poke Bowl",
    image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    ingredients: [
      "1 lb sushi-grade ahi tuna, cubed",
      "1/4 cup soy sauce",
      "2 tbsp sesame oil",
      "1 tbsp rice vinegar",
      "1 tsp sriracha (optional)",
      "1 tbsp toasted sesame seeds",
      "3 green onions, thinly sliced",
      "1/2 sweet onion, thinly sliced",
      "1 avocado, sliced",
      "1 cucumber, sliced",
      "2 cups cooked short-grain rice",
      "1 sheet nori, cut into strips",
      "1 tsp sea salt flakes",
      "1 tbsp macadamia nuts, chopped",
      "Pickled ginger for serving"
    ],
    steps: [
      "In a medium bowl, combine soy sauce, sesame oil, rice vinegar, and sriracha (if using).",
      "Add cubed tuna to the marinade, gently toss to coat. Refrigerate for 15-30 minutes.",
      "Before serving, add green onions, sweet onion, and sesame seeds to the tuna mixture.",
      "Divide cooked rice between two bowls.",
      "Arrange marinated tuna over rice.",
      "Add avocado and cucumber slices around the tuna.",
      "Sprinkle with sea salt flakes, chopped macadamia nuts, and nori strips.",
      "Serve with pickled ginger on the side."
    ],
    cuisine: "Hawaiian",
    tags: ["Seafood", "Bowl", "Healthy"],
    prepTime: 30
  },
  {
    id: "greek-moussaka",
    title: "Greek Moussaka",
    image: "https://images.unsplash.com/photo-1617711830036-41a8d4336aa0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    ingredients: [
      "3 eggplants, sliced into 1/2-inch rounds",
      "Salt for drawing out eggplant moisture",
      "Olive oil for brushing",
      
      "For meat sauce:",
      "2 tbsp olive oil",
      "1 large onion, chopped",
      "2 cloves garlic, minced",
      "1.5 lbs ground lamb (or beef)",
      "1 can (14 oz) diced tomatoes",
      "2 tbsp tomato paste",
      "1 cinnamon stick",
      "1/4 tsp ground allspice",
      "1/4 tsp ground cloves",
      "1/2 cup red wine",
      "2 tbsp fresh parsley, chopped",
      "Salt and pepper to taste",
      
      "For béchamel sauce:",
      "1/2 cup butter",
      "1/2 cup all-purpose flour",
      "3 cups warm milk",
      "1/4 tsp ground nutmeg",
      "2 egg yolks",
      "1/2 cup grated Parmesan cheese",
      "Salt and pepper to taste"
    ],
    steps: [
      "Sprinkle eggplant slices with salt and place in a colander for 30 minutes to draw out moisture. Rinse and pat dry.",
      "Preheat oven to 400°F. Brush eggplant slices with olive oil and arrange on baking sheets.",
      "Roast eggplant for 20-25 minutes until soft and lightly browned. Set aside and reduce oven to 350°F.",
      "Make meat sauce: Heat olive oil in a large skillet over medium heat. Add onions and garlic, sauté until soft.",
      "Add ground lamb and cook until browned, breaking up the meat.",
      "Add diced tomatoes, tomato paste, cinnamon stick, allspice, cloves, and red wine. Simmer for 20-30 minutes until thickened.",
      "Remove cinnamon stick, stir in parsley, and season with salt and pepper.",
      "Make béchamel sauce: Melt butter in a saucepan over medium heat. Add flour and whisk for 1-2 minutes.",
      "Gradually whisk in warm milk and cook until thickened, about 5-8 minutes.",
      "Remove from heat and whisk in nutmeg, egg yolks, and half the Parmesan cheese. Season with salt and pepper.",
      "Assemble moussaka: In a 9x13-inch baking dish, arrange half the eggplant slices. Top with all of the meat sauce, then the remaining eggplant.",
      "Pour béchamel sauce over the top and sprinkle with remaining Parmesan cheese.",
      "Bake for 45-50 minutes until top is golden brown.",
      "Let rest for 15-20 minutes before serving."
    ],
    cuisine: "Greek",
    tags: ["Casserole", "Comfort Food", "Traditional"],
    prepTime: 120
  }
];

export default additionalRecipes;
