// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whcgaaryfcxkzhbpltyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoY2dhYXJ5ZmN4a3poYnBsdHlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTE2NTIsImV4cCI6MjA2MTc2NzY1Mn0.MD7Qyrt5whKuaBDoT4sVHUp7CJ3PdjE0r3q7NSK0_K4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);